### ISSUE TITLE
Unknown sources for some domains

### ISSUE THREAD

**Issue by ssardina** [AI-Planning/fond-domains#4]
@haz while I was hunting the origins of FOND domains, I couldn't find the origin of some of them that seem to have be born in your PRP repo, but that they are not reported in the 2012 PRP paper. :confused: 

I was able to find the sources for many (e.g., `beam_walk` or `chain-of-rooms`, `earth-observation`; see Misc Domains section) but some are still unclear to me:

- [x] `acrobatics`: the inline comment is that it comes from Miquel Ramirez in 2014 as a twist of beam-walk. Couldn't find a paper source.
- [x] `blocksworld-2`
- [x] `ex-blocksworld`
- [x] `first-reponders-new`
- [x] `puffbot_dialogue_pddl`: you had a comment but couldn't find where, is this personal communication?
- [x] all the domains starting with prefix `st_xxx`: they must have some common description?
- [x] `tidyup-mdp`: there is a `tidyup` deterministic. Are these coming from [here](https://cdn.aaai.org/ocs/5749/5749-24510-1-PB.pdf)?
- [x] `tireworld`: I found its first reference in an [example](https://ipc08.icaps-conference.org/probabilistic/wiki/index.php/Tireworld_p01.html) for the IPC-6 (2008) FOND track; seems not used in the competition itself but PDDL was there already. Fixed the inline comment to reflect that and added URL

**Comment by haz** [comment]
Heh, digging deep now...

## blocksworld-2 / ex-blocksworld
These are from the probabilistic track of IPC'06 ( https://ipc06.icaps-conference.org/probabilistic/ )

Note that the latest commit message on this page is useful: https://github.com/QuMuLab/planner-for-relevant-policies/tree/master/fond-benchmarks

## first-responders-new
Same as the forest-new, etc. These were expanded sets of the benchmark to scale much larger (since PRP was solving the original all too quickly). Blocks and Forest were in the original PRP paper, but the others came later just as a means of scaling. Looks like hit or miss as to which FOND papers included them (looks like most skip forest altogether?). 🤷 

## puffbot
As mentioned in the README, this is from Milene Teixeira's work. Her thesis is [[here](https://iris.unitn.it/retrieve/handle/11572/361402/595412/phd_unitn_santos_teixeira_milene.pdf)], but the PDDL came to me via personal correspondence (I was granted permission to add it to a public benchmark suite).

## st_xxx

Fun one...had to dig for this a bit. My original thought was on my unpublished (<grumbles at reviewers>) strong cyclic -> acyclic approach. It actually turns out to be from this: https://www.hlt.utdallas.edu/~vince/papers/ictai13.pdf

Found the email where I asked explicitly for them, and the originals were already determinized. I modified them to place back into FOND form. The one exception is st_mapfdu. That comes from this work: https://cdn.aaai.org/ojs/6204/6204-13-9429-1-10-20200516.pdf

## tidyup-mdp

This came in from MyND when I merged all the FOND planner benchmarks. You can find it here: https://bitbucket.org/robertmattmueller/mynd/src/master/data/fond-pddl/tidyup-mdp/

Don't know of the origin beyond that (but I did have to clean it up a bit :P)

**Comment by ssardina** [comment]
> blocksworld-2 / ex-blocksworld
> 
> These are from the probabilistic track of IPC'06 ( https://ipc06.icaps-conference.org/probabilistic/ )
> 
> Note that the latest commit message on this page is useful: https://github.com/QuMuLab/planner-for-relevant-policies/tree/master/fond-benchmarks


I had a closer look. The three `blocksworld`, `blocksworld-new` and `blocks-world-2` are basically the same domain, and the (oneof) already appeared in the FOND track in IPC-6 (2008). They already got the probabilistic version and used `(oneof)` instead in IPC-6. So:

- `blocksworld`: FOND version in IPC-6
- `blocksworld-new`: PRP scaled up version of `blocksworld`
- `blocksworld-2`: the `oneof` version of the 15 instances used in the IPC-6 probabilistic track.


Now, `ex-blocksworld` is indeed different, as blocks can explode. This is a  `(oneof)` version of the IPC-6 probabilistic track. 

I have renamed it `blocksworld-ex` so that they are listed all together.

**Comment by ssardina** [comment]
cleaned-up `puffbot` and added links to the sources (including a 2021 paper) and rename folder to match domain name in PDDL :smile:

**Comment by ssardina** [comment]
all `st_xxx` domains processed; they are all domains that admit _strong_ solutions

**Comment by ssardina** [comment]
OK @haz , I have incorporated all your feedback and a bit more I found on the way into README and source files.

I think this is done. We can continue in PR #3
